const storeKey = 'fluir-study-tasks-v1';
const defaultTasks = [
  { id: 1, title: 'Revisar anotações de Psicologia', time: '09:00', priority: 'high', note: 'Comece pelos conceitos destacados', reminder: true, done: false },
  { id: 2, title: 'Resolver lista de Cálculo', time: '11:00', priority: 'high', note: 'Faça primeiro as questões 1 e 2', reminder: true, done: false },
  { id: 3, title: 'Pausa para almoçar', time: '12:30', priority: 'low', note: 'Descanso também faz parte do plano', reminder: false, done: false },
  { id: 4, title: 'Ler artigo para o seminário', time: '15:00', priority: 'medium', note: 'Sublinhe apenas as ideias centrais', reminder: true, done: false }
];
const defaultRoutine = [
  ['🌤️', 'Preparar o dia', 'Ver tarefas e separar o material'],
  ['💧', 'Água e uma pausa', 'A cada bloco de foco'],
  ['📵', 'Celular em outro lugar', 'Durante a tarefa mais importante'],
  ['🌙', 'Fechar o dia', 'Anotar o primeiro passo de amanhã']
];
let tasks = JSON.parse(localStorage.getItem(storeKey) || 'null') || defaultTasks;
let routine = JSON.parse(localStorage.getItem('fluir-routine-v1') || 'null') || defaultRoutine.map((r, i) => ({id:i, icon:r[0], title:r[1], desc:r[2], done:false}));
let filter = 'all', timerSeconds = 25 * 60, timerId = null, soundOn = true;
const $ = (s) => document.querySelector(s);
const pad = n => String(n).padStart(2, '0');
function save(){ localStorage.setItem(storeKey, JSON.stringify(tasks)); localStorage.setItem('fluir-routine-v1', JSON.stringify(routine)); }
function formatDate(){ const d = new Date(); $('#date-label').textContent = d.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}).toUpperCase(); }
function showToast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(el._timeout); el._timeout=setTimeout(()=>el.classList.remove('show'),3500); }
function beep(){ if(!soundOn) return; try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=660;g.gain.setValueAtTime(.1,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.5);o.start();o.stop(c.currentTime+.5)}catch(e){} }
function priorityLabel(p){return ({high:'Alta',medium:'Média',low:'Baixa'})[p]}
function renderTasks(){ const filtered=tasks.filter(t=>filter==='all'||filter==='done'?filter==='done'?t.done:true:t.priority===filter); const list=$('#task-list'); list.innerHTML=filtered.map(t=>`<article class="task-item ${t.done?'done':''}"><input class="check" type="checkbox" data-id="${t.id}" ${t.done?'checked':''} aria-label="Concluir ${t.title}"><div class="task-main"><p class="task-title"><span class="priority-dot priority-${t.priority}" aria-hidden="true"></span>${escapeHTML(t.title)}</p>${t.note?`<p class="task-note">${escapeHTML(t.note)}</p>`:''}</div><span class="time-pill">${t.time}</span><button class="remove-task" type="button" data-remove="${t.id}" aria-label="Remover ${t.title}">×</button></article>`).join(''); $('#empty-state').hidden=filtered.length!==0; $('#task-count').textContent=tasks.filter(t=>!t.done).length; const total=tasks.length, done=tasks.filter(t=>t.done).length, pct=total?Math.round(done/total*100):0; $('#progress-bar').style.width=pct+'%'; $('.progress-track').setAttribute('aria-valuenow',pct); $('#progress-value').textContent=pct+'%'; $('#progress-copy').textContent=done ? `${done} de ${total} tarefa${total!==1?'s':''} concluída${done!==1?'s':''}.` : 'Ainda tem espaço para um bom começo.'; const next=tasks.filter(t=>!t.done).sort((a,b)=>a.time.localeCompare(b.time))[0]; $('#next-task-text').textContent=next?`${next.title} às ${next.time}`:'Você cuidou de tudo. Que tal uma pausa?'; renderWeek(); }
function escapeHTML(str){const d=document.createElement('div');d.textContent=str;return d.innerHTML}
function renderWeek(){ const grid=$('#week-grid'); if(!grid)return; const now=new Date(); const monday=new Date(now); monday.setDate(now.getDate()-(now.getDay()+6)%7); const names=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']; grid.innerHTML=names.map((name,i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);const isToday=date.toDateString()===now.toDateString();const items=i===0?tasks.slice(0,5):[];return `<section class="day-column ${isToday?'today':''}"><div class="day-name">${name}</div><div class="day-number">${date.getDate()}</div>${items.length?items.map(t=>`<div class="mini-task ${t.priority}">${t.time} · ${escapeHTML(t.title)}</div>`).join(''):'<p class="mini-empty">Livre para respirar</p>'}</section>`}).join(''); }
function renderRoutine(){ $('#routine-list').innerHTML=routine.map(r=>`<label class="routine-item"><input type="checkbox" data-routine="${r.id}" ${r.done?'checked':''}><span>${r.icon}</span><p>${r.title}<small>${r.desc}</small></p></label>`).join(''); }
function renderTimer(){ $('#timer-display').textContent=`${pad(Math.floor(timerSeconds/60))}:${pad(timerSeconds%60)}`; $('#timer-toggle').textContent=timerId?'Ⅱ':'▶'; $('#timer-toggle').setAttribute('aria-label',timerId?'Pausar cronômetro':'Iniciar cronômetro'); }
function toggleTimer(){ if(timerId){clearInterval(timerId);timerId=null;renderTimer();return} timerId=setInterval(()=>{timerSeconds--;if(timerSeconds<=0){clearInterval(timerId);timerId=null;timerSeconds=25*60;beep();showToast('Bloco concluído! Respire, beba água e celebre. ✨')}renderTimer()},1000);renderTimer(); }
function addTask(data){tasks.push({id:Date.now(),...data,done:false});tasks.sort((a,b)=>a.time.localeCompare(b.time));save();renderTasks();showToast('Tarefa salva. Você consegue! ✦');}
function checkReminders(){ const now=new Date(),time=`${pad(now.getHours())}:${pad(now.getMinutes())}`; tasks.filter(t=>t.reminder&&!t.done&&t.time===time&&!t.reminded).forEach(t=>{t.reminded=true;save();beep();showToast(`Hora de ${t.title} — ${t.note||'comece pelo menor passo.'}`);if('Notification'in window&&Notification.permission==='granted')new Notification('Fluir', {body:`Hora de ${t.title}`});}); }
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-link');if(nav){e.preventDefault();document.querySelectorAll('.nav-link,.view').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$(`#${nav.dataset.view}-view`).classList.add('active');} const filterBtn=e.target.closest('.filter');if(filterBtn){filter=filterBtn.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===filterBtn));renderTasks()} const rm=e.target.closest('[data-remove]');if(rm){tasks=tasks.filter(t=>t.id!==Number(rm.dataset.remove));save();renderTasks();showToast('Tarefa removida.')}});
$('#task-list').addEventListener('change',e=>{if(e.target.matches('[data-id]')){const task=tasks.find(t=>t.id===Number(e.target.dataset.id));task.done=e.target.checked;save();renderTasks();if(task.done){beep();showToast('Feito! Pequenas vitórias contam. 🌟')}}});
$('#routine-list').addEventListener('change',e=>{if(e.target.matches('[data-routine]')){routine.find(r=>r.id===Number(e.target.dataset.routine)).done=e.target.checked;save();renderRoutine()}});
$('#open-task-modal').onclick=()=>$('#task-modal').showModal();$('#close-modal').onclick=$('#cancel-modal').onclick=()=>$('#task-modal').close();
$('#task-form').addEventListener('submit',e=>{e.preventDefault();const data={title:$('#task-title').value.trim(),time:$('#task-time').value,priority:$('#task-priority').value,note:$('#task-note').value.trim(),reminder:$('#task-reminder').checked};if(!data.title)return;addTask(data);$('#task-form').reset();$('#task-time').value='09:00';$('#task-modal').close();if(data.reminder&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission();});
$('#timer-toggle').onclick=toggleTimer;$('#timer-reset').onclick=()=>{clearInterval(timerId);timerId=null;timerSeconds=25*60;renderTimer();showToast('Cronômetro reiniciado. Recomeçar também é válido.')};$('#start-next').onclick=()=>{if(!timerId)toggleTimer();showToast('Modo foco ligado: uma tarefa, um passo de cada vez.');};$('#sound-toggle').onclick=e=>{soundOn=!soundOn;e.currentTarget.setAttribute('aria-pressed',soundOn);e.currentTarget.textContent=soundOn?'🔔 Lembretes ligados':'🔕 Lembretes desligados';showToast(soundOn?'Lembretes ativados.':'Lembretes silenciados.')};
$('#add-routine').onclick=()=>{const title=prompt('Qual hábito você quer adicionar?');if(title?.trim()){routine.push({id:Date.now(),icon:'✨',title:title.trim(),desc:'Um lembrete gentil para você',done:false});save();renderRoutine();}};
formatDate();renderTasks();renderRoutine();renderTimer();checkReminders();setInterval(checkReminders,30000);
